version: '3.8'

services:
  gateway_service:
    container_name: gateway_cont
    build: ./
    ports:
      - "8080:8080"
    networks:
      - global-network

networks:
  global-network:
    external: true
    # name: global-network
