version: '3.8'

services:
  auth-service:
    container_name: auth_service 
    build: ./
    ports:
      - "8088:8088"
    networks:
      - global-network
    depends_on:
      - postgres-service
      - redis

  migrate:
    image: migrate/migrate
    networks:
      - global-network
    volumes:
      - ./migrations:/migrations
    command: [ "-path", "/migrations", "-database",  "postgres://postgres:root@postgres_cont:5432/finance_auth?sslmode=disable", "up" ]
    depends_on:
      - postgres-service

  postgres-service:
    container_name: postgres_cont
    image: postgres:latest
    environment:
      PGUSER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: finance_auth
    ports:
      - "5433:5432"
    networks:
      - global-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres"]
      interval: 30s
      timeout: 10s
      retries: 5
    
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data
    networks:
      - global-network

networks:
  global-network:
    external: true
    name: global-network
    driver: bridge

volumes:
  redis-data: