// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.21.1
// source: finance-protos/account.proto

package genprotos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AccountGRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name   string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Type   string `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *AccountGRes) Reset() {
	*x = AccountGRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_finance_protos_account_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountGRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountGRes) ProtoMessage() {}

func (x *AccountGRes) ProtoReflect() protoreflect.Message {
	mi := &file_finance_protos_account_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountGRes.ProtoReflect.Descriptor instead.
func (*AccountGRes) Descriptor() ([]byte, []int) {
	return file_finance_protos_account_proto_rawDescGZIP(), []int{0}
}

func (x *AccountGRes) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AccountGRes) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AccountGRes) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AccountGRes) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type AccountBalanceGRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Currency string  `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	Balance  float32 `protobuf:"fixed32,6,opt,name=balance,proto3" json:"balance,omitempty"`
}

func (x *AccountBalanceGRes) Reset() {
	*x = AccountBalanceGRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_finance_protos_account_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountBalanceGRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountBalanceGRes) ProtoMessage() {}

func (x *AccountBalanceGRes) ProtoReflect() protoreflect.Message {
	mi := &file_finance_protos_account_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountBalanceGRes.ProtoReflect.Descriptor instead.
func (*AccountBalanceGRes) Descriptor() ([]byte, []int) {
	return file_finance_protos_account_proto_rawDescGZIP(), []int{1}
}

func (x *AccountBalanceGRes) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *AccountBalanceGRes) GetBalance() float32 {
	if x != nil {
		return x.Balance
	}
	return 0
}

type AccountBalanceUReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId  string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Balance string `protobuf:"bytes,2,opt,name=balance,proto3" json:"balance,omitempty"`
}

func (x *AccountBalanceUReq) Reset() {
	*x = AccountBalanceUReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_finance_protos_account_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountBalanceUReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountBalanceUReq) ProtoMessage() {}

func (x *AccountBalanceUReq) ProtoReflect() protoreflect.Message {
	mi := &file_finance_protos_account_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountBalanceUReq.ProtoReflect.Descriptor instead.
func (*AccountBalanceUReq) Descriptor() ([]byte, []int) {
	return file_finance_protos_account_proto_rawDescGZIP(), []int{2}
}

func (x *AccountBalanceUReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AccountBalanceUReq) GetBalance() string {
	if x != nil {
		return x.Balance
	}
	return ""
}

type AccountUReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *AccountUReq) Reset() {
	*x = AccountUReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_finance_protos_account_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountUReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountUReq) ProtoMessage() {}

func (x *AccountUReq) ProtoReflect() protoreflect.Message {
	mi := &file_finance_protos_account_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountUReq.ProtoReflect.Descriptor instead.
func (*AccountUReq) Descriptor() ([]byte, []int) {
	return file_finance_protos_account_proto_rawDescGZIP(), []int{3}
}

func (x *AccountUReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AccountUReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_finance_protos_account_proto protoreflect.FileDescriptor

var file_finance_protos_account_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x66, 0x69, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73,
	0x2f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07,
	0x66, 0x69, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x1a, 0x19, 0x66, 0x69, 0x6e, 0x61, 0x6e, 0x63, 0x65,
	0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x76, 0x6f, 0x69, 0x64, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x5e, 0x0a, 0x0b, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x47, 0x52, 0x65,
	0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x22, 0x4a, 0x0a, 0x12, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x42, 0x61, 0x6c,
	0x61, 0x6e, 0x63, 0x65, 0x47, 0x52, 0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x75, 0x72, 0x72,
	0x65, 0x6e, 0x63, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x75, 0x72, 0x72,
	0x65, 0x6e, 0x63, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x02, 0x52, 0x07, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x22, 0x47,
	0x0a, 0x12, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65,
	0x55, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x18, 0x0a,
	0x07, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x22, 0x31, 0x0a, 0x0b, 0x41, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x55, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x32, 0xf8, 0x01, 0x0a, 0x0e, 0x41,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x35, 0x0a,
	0x0a, 0x47, 0x65, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x11, 0x2e, 0x66, 0x69,
	0x6e, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x1a, 0x14,
	0x2e, 0x66, 0x69, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x47, 0x52, 0x65, 0x73, 0x12, 0x3c, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x42, 0x61, 0x6c, 0x61, 0x6e,
	0x63, 0x65, 0x12, 0x11, 0x2e, 0x66, 0x69, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x42, 0x79, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x44, 0x1a, 0x1b, 0x2e, 0x66, 0x69, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x2e,
	0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x47, 0x52,
	0x65, 0x73, 0x12, 0x34, 0x0a, 0x0d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x14, 0x2e, 0x66, 0x69, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x41, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x55, 0x52, 0x65, 0x71, 0x1a, 0x0d, 0x2e, 0x66, 0x69, 0x6e, 0x61,
	0x6e, 0x63, 0x65, 0x2e, 0x56, 0x6f, 0x69, 0x64, 0x12, 0x3b, 0x0a, 0x0d, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x1b, 0x2e, 0x66, 0x69, 0x6e, 0x61,
	0x6e, 0x63, 0x65, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x42, 0x61, 0x6c, 0x61, 0x6e,
	0x63, 0x65, 0x55, 0x52, 0x65, 0x71, 0x1a, 0x0d, 0x2e, 0x66, 0x69, 0x6e, 0x61, 0x6e, 0x63, 0x65,
	0x2e, 0x56, 0x6f, 0x69, 0x64, 0x42, 0x0c, 0x5a, 0x0a, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x73, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_finance_protos_account_proto_rawDescOnce sync.Once
	file_finance_protos_account_proto_rawDescData = file_finance_protos_account_proto_rawDesc
)

func file_finance_protos_account_proto_rawDescGZIP() []byte {
	file_finance_protos_account_proto_rawDescOnce.Do(func() {
		file_finance_protos_account_proto_rawDescData = protoimpl.X.CompressGZIP(file_finance_protos_account_proto_rawDescData)
	})
	return file_finance_protos_account_proto_rawDescData
}

var file_finance_protos_account_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_finance_protos_account_proto_goTypes = []any{
	(*AccountGRes)(nil),        // 0: finance.AccountGRes
	(*AccountBalanceGRes)(nil), // 1: finance.AccountBalanceGRes
	(*AccountBalanceUReq)(nil), // 2: finance.AccountBalanceUReq
	(*AccountUReq)(nil),        // 3: finance.AccountUReq
	(*ByUserID)(nil),           // 4: finance.ByUserID
	(*Void)(nil),               // 5: finance.Void
}
var file_finance_protos_account_proto_depIdxs = []int32{
	4, // 0: finance.AccountService.GetAccount:input_type -> finance.ByUserID
	4, // 1: finance.AccountService.GetBalance:input_type -> finance.ByUserID
	3, // 2: finance.AccountService.UpdateAccount:input_type -> finance.AccountUReq
	2, // 3: finance.AccountService.UpdateBalance:input_type -> finance.AccountBalanceUReq
	0, // 4: finance.AccountService.GetAccount:output_type -> finance.AccountGRes
	1, // 5: finance.AccountService.GetBalance:output_type -> finance.AccountBalanceGRes
	5, // 6: finance.AccountService.UpdateAccount:output_type -> finance.Void
	5, // 7: finance.AccountService.UpdateBalance:output_type -> finance.Void
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_finance_protos_account_proto_init() }
func file_finance_protos_account_proto_init() {
	if File_finance_protos_account_proto != nil {
		return
	}
	file_finance_protos_void_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_finance_protos_account_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*AccountGRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_finance_protos_account_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*AccountBalanceGRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_finance_protos_account_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*AccountBalanceUReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_finance_protos_account_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*AccountUReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_finance_protos_account_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_finance_protos_account_proto_goTypes,
		DependencyIndexes: file_finance_protos_account_proto_depIdxs,
		MessageInfos:      file_finance_protos_account_proto_msgTypes,
	}.Build()
	File_finance_protos_account_proto = out.File
	file_finance_protos_account_proto_rawDesc = nil
	file_finance_protos_account_proto_goTypes = nil
	file_finance_protos_account_proto_depIdxs = nil
}
