// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.21.1
// source: finance-protos/category.proto

package genprotos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CategoryCReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name   string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type   string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *CategoryCReq) Reset() {
	*x = CategoryCReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_finance_protos_category_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CategoryCReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryCReq) ProtoMessage() {}

func (x *CategoryCReq) ProtoReflect() protoreflect.Message {
	mi := &file_finance_protos_category_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryCReq.ProtoReflect.Descriptor instead.
func (*CategoryCReq) Descriptor() ([]byte, []int) {
	return file_finance_protos_category_proto_rawDescGZIP(), []int{0}
}

func (x *CategoryCReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CategoryCReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CategoryCReq) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type CategoryCReqForSwagger struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *CategoryCReqForSwagger) Reset() {
	*x = CategoryCReqForSwagger{}
	if protoimpl.UnsafeEnabled {
		mi := &file_finance_protos_category_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CategoryCReqForSwagger) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryCReqForSwagger) ProtoMessage() {}

func (x *CategoryCReqForSwagger) ProtoReflect() protoreflect.Message {
	mi := &file_finance_protos_category_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryCReqForSwagger.ProtoReflect.Descriptor instead.
func (*CategoryCReqForSwagger) Descriptor() ([]byte, []int) {
	return file_finance_protos_category_proto_rawDescGZIP(), []int{1}
}

func (x *CategoryCReqForSwagger) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CategoryCReqForSwagger) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type CategoryUReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *CategoryUReq) Reset() {
	*x = CategoryUReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_finance_protos_category_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CategoryUReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryUReq) ProtoMessage() {}

func (x *CategoryUReq) ProtoReflect() protoreflect.Message {
	mi := &file_finance_protos_category_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryUReq.ProtoReflect.Descriptor instead.
func (*CategoryUReq) Descriptor() ([]byte, []int) {
	return file_finance_protos_category_proto_rawDescGZIP(), []int{2}
}

func (x *CategoryUReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CategoryUReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CategoryUReqForSwagger struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *CategoryUReqForSwagger) Reset() {
	*x = CategoryUReqForSwagger{}
	if protoimpl.UnsafeEnabled {
		mi := &file_finance_protos_category_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CategoryUReqForSwagger) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryUReqForSwagger) ProtoMessage() {}

func (x *CategoryUReqForSwagger) ProtoReflect() protoreflect.Message {
	mi := &file_finance_protos_category_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryUReqForSwagger.ProtoReflect.Descriptor instead.
func (*CategoryUReqForSwagger) Descriptor() ([]byte, []int) {
	return file_finance_protos_category_proto_rawDescGZIP(), []int{3}
}

func (x *CategoryUReqForSwagger) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CategoryGRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name   string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Type   string `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *CategoryGRes) Reset() {
	*x = CategoryGRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_finance_protos_category_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CategoryGRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryGRes) ProtoMessage() {}

func (x *CategoryGRes) ProtoReflect() protoreflect.Message {
	mi := &file_finance_protos_category_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryGRes.ProtoReflect.Descriptor instead.
func (*CategoryGRes) Descriptor() ([]byte, []int) {
	return file_finance_protos_category_proto_rawDescGZIP(), []int{4}
}

func (x *CategoryGRes) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CategoryGRes) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CategoryGRes) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CategoryGRes) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type CategoryGAReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId     string      `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Pagination *Pagination `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (x *CategoryGAReq) Reset() {
	*x = CategoryGAReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_finance_protos_category_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CategoryGAReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryGAReq) ProtoMessage() {}

func (x *CategoryGAReq) ProtoReflect() protoreflect.Message {
	mi := &file_finance_protos_category_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryGAReq.ProtoReflect.Descriptor instead.
func (*CategoryGAReq) Descriptor() ([]byte, []int) {
	return file_finance_protos_category_proto_rawDescGZIP(), []int{5}
}

func (x *CategoryGAReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CategoryGAReq) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type CategoryGARes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Categories []*CategoryGRes `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
}

func (x *CategoryGARes) Reset() {
	*x = CategoryGARes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_finance_protos_category_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CategoryGARes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryGARes) ProtoMessage() {}

func (x *CategoryGARes) ProtoReflect() protoreflect.Message {
	mi := &file_finance_protos_category_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryGARes.ProtoReflect.Descriptor instead.
func (*CategoryGARes) Descriptor() ([]byte, []int) {
	return file_finance_protos_category_proto_rawDescGZIP(), []int{6}
}

func (x *CategoryGARes) GetCategories() []*CategoryGRes {
	if x != nil {
		return x.Categories
	}
	return nil
}

var File_finance_protos_category_proto protoreflect.FileDescriptor

var file_finance_protos_category_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x66, 0x69, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73,
	0x2f, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x66, 0x69, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x1a, 0x19, 0x66, 0x69, 0x6e, 0x61, 0x6e, 0x63,
	0x65, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x76, 0x6f, 0x69, 0x64, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x4f, 0x0a, 0x0c, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x43,
	0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x22, 0x40, 0x0a, 0x16, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79,
	0x43, 0x52, 0x65, 0x71, 0x46, 0x6f, 0x72, 0x53, 0x77, 0x61, 0x67, 0x67, 0x65, 0x72, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x32, 0x0a, 0x0c, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f,
	0x72, 0x79, 0x55, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x2c, 0x0a, 0x16, 0x43, 0x61,
	0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x55, 0x52, 0x65, 0x71, 0x46, 0x6f, 0x72, 0x53, 0x77, 0x61,
	0x67, 0x67, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x5f, 0x0a, 0x0c, 0x43, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x79, 0x47, 0x52, 0x65, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x5d, 0x0a, 0x0d, 0x43, 0x61, 0x74,
	0x65, 0x67, 0x6f, 0x72, 0x79, 0x47, 0x41, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x33, 0x0a, 0x0a, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x66, 0x69, 0x6e, 0x61, 0x6e, 0x63,
	0x65, 0x2e, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0a, 0x70, 0x61,
	0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x46, 0x0a, 0x0d, 0x43, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x79, 0x47, 0x41, 0x52, 0x65, 0x73, 0x12, 0x35, 0x0a, 0x0a, 0x63, 0x61, 0x74,
	0x65, 0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e,
	0x66, 0x69, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79,
	0x47, 0x52, 0x65, 0x73, 0x52, 0x0a, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x65, 0x73,
	0x32, 0x84, 0x02, 0x0a, 0x0f, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x2e, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x15,
	0x2e, 0x66, 0x69, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72,
	0x79, 0x43, 0x52, 0x65, 0x71, 0x1a, 0x0d, 0x2e, 0x66, 0x69, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x2e,
	0x56, 0x6f, 0x69, 0x64, 0x12, 0x2f, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x42, 0x79, 0x49, 0x44, 0x12,
	0x0d, 0x2e, 0x66, 0x69, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x42, 0x79, 0x49, 0x44, 0x1a, 0x15,
	0x2e, 0x66, 0x69, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72,
	0x79, 0x47, 0x52, 0x65, 0x73, 0x12, 0x2e, 0x0a, 0x06, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12,
	0x15, 0x2e, 0x66, 0x69, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f,
	0x72, 0x79, 0x55, 0x52, 0x65, 0x71, 0x1a, 0x0d, 0x2e, 0x66, 0x69, 0x6e, 0x61, 0x6e, 0x63, 0x65,
	0x2e, 0x56, 0x6f, 0x69, 0x64, 0x12, 0x26, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12,
	0x0d, 0x2e, 0x66, 0x69, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x42, 0x79, 0x49, 0x44, 0x1a, 0x0d,
	0x2e, 0x66, 0x69, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x56, 0x6f, 0x69, 0x64, 0x12, 0x38, 0x0a,
	0x06, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x12, 0x16, 0x2e, 0x66, 0x69, 0x6e, 0x61, 0x6e, 0x63,
	0x65, 0x2e, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x47, 0x41, 0x52, 0x65, 0x71, 0x1a,
	0x16, 0x2e, 0x66, 0x69, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f,
	0x72, 0x79, 0x47, 0x41, 0x52, 0x65, 0x73, 0x42, 0x0c, 0x5a, 0x0a, 0x67, 0x65, 0x6e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_finance_protos_category_proto_rawDescOnce sync.Once
	file_finance_protos_category_proto_rawDescData = file_finance_protos_category_proto_rawDesc
)

func file_finance_protos_category_proto_rawDescGZIP() []byte {
	file_finance_protos_category_proto_rawDescOnce.Do(func() {
		file_finance_protos_category_proto_rawDescData = protoimpl.X.CompressGZIP(file_finance_protos_category_proto_rawDescData)
	})
	return file_finance_protos_category_proto_rawDescData
}

var file_finance_protos_category_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_finance_protos_category_proto_goTypes = []any{
	(*CategoryCReq)(nil),           // 0: finance.CategoryCReq
	(*CategoryCReqForSwagger)(nil), // 1: finance.CategoryCReqForSwagger
	(*CategoryUReq)(nil),           // 2: finance.CategoryUReq
	(*CategoryUReqForSwagger)(nil), // 3: finance.CategoryUReqForSwagger
	(*CategoryGRes)(nil),           // 4: finance.CategoryGRes
	(*CategoryGAReq)(nil),          // 5: finance.CategoryGAReq
	(*CategoryGARes)(nil),          // 6: finance.CategoryGARes
	(*Pagination)(nil),             // 7: finance.Pagination
	(*ByID)(nil),                   // 8: finance.ByID
	(*Void)(nil),                   // 9: finance.Void
}
var file_finance_protos_category_proto_depIdxs = []int32{
	7, // 0: finance.CategoryGAReq.pagination:type_name -> finance.Pagination
	4, // 1: finance.CategoryGARes.categories:type_name -> finance.CategoryGRes
	0, // 2: finance.CategoryService.Create:input_type -> finance.CategoryCReq
	8, // 3: finance.CategoryService.GetByID:input_type -> finance.ByID
	2, // 4: finance.CategoryService.Update:input_type -> finance.CategoryUReq
	8, // 5: finance.CategoryService.Delete:input_type -> finance.ByID
	5, // 6: finance.CategoryService.GetAll:input_type -> finance.CategoryGAReq
	9, // 7: finance.CategoryService.Create:output_type -> finance.Void
	4, // 8: finance.CategoryService.GetByID:output_type -> finance.CategoryGRes
	9, // 9: finance.CategoryService.Update:output_type -> finance.Void
	9, // 10: finance.CategoryService.Delete:output_type -> finance.Void
	6, // 11: finance.CategoryService.GetAll:output_type -> finance.CategoryGARes
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_finance_protos_category_proto_init() }
func file_finance_protos_category_proto_init() {
	if File_finance_protos_category_proto != nil {
		return
	}
	file_finance_protos_void_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_finance_protos_category_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*CategoryCReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_finance_protos_category_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*CategoryCReqForSwagger); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_finance_protos_category_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*CategoryUReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_finance_protos_category_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*CategoryUReqForSwagger); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_finance_protos_category_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*CategoryGRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_finance_protos_category_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*CategoryGAReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_finance_protos_category_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*CategoryGARes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_finance_protos_category_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_finance_protos_category_proto_goTypes,
		DependencyIndexes: file_finance_protos_category_proto_depIdxs,
		MessageInfos:      file_finance_protos_category_proto_msgTypes,
	}.Build()
	File_finance_protos_category_proto = out.File
	file_finance_protos_category_proto_rawDesc = nil
	file_finance_protos_category_proto_goTypes = nil
	file_finance_protos_category_proto_depIdxs = nil
}
