definitions:
  genprotos.CheckReq:
    properties:
      correct_answer:
        type: string
      exercise_id:
        type: string
    type: object
  genprotos.ExerciseGARes:
    properties:
      count:
        type: integer
      exercises:
        items:
          $ref: '#/definitions/genprotos.ExerciseGResUReq'
        type: array
    type: object
  genprotos.ExerciseGResUReq:
    properties:
      correct_answer:
        type: string
      id:
        type: string
      lesson_id:
        type: string
      options:
        type: string
      question:
        type: string
      type:
        type: string
    type: object
  genprotos.LeadboardRes:
    properties:
      users:
        items:
          $ref: '#/definitions/genprotos.LeadboardUserRes'
        type: array
    type: object
  genprotos.LeadboardUserRes:
    properties:
      daily_streak:
        type: integer
      level:
        type: string
      native_lang:
        type: string
      played_games_count:
        type: integer
      user_id:
        type: string
      winning_percentage:
        type: number
      xp:
        type: integer
    type: object
  genprotos.LessonCReqGRes:
    properties:
      content:
        type: string
      id:
        type: string
      lang_1:
        type: string
      lang_2:
        type: string
      level:
        type: string
      name:
        type: string
      order:
        type: integer
      title:
        type: string
    type: object
  genprotos.LessonGARes:
    properties:
      count:
        type: integer
      lessons:
        items:
          $ref: '#/definitions/genprotos.LessonCReqGRes'
        type: array
    type: object
  genprotos.TestCheckReqForSwagger:
    properties:
      lesson_id:
        type: string
      requests:
        items:
          $ref: '#/definitions/genprotos.CheckReq'
        type: array
    type: object
  genprotos.TestResultRes:
    properties:
      correct_answers_count:
        type: integer
      feedback:
        type: string
      tests_count:
        type: integer
      xp_given:
        type: integer
    type: object
  genprotos.UserDataGRes:
    properties:
      daily_streak:
        type: integer
      level:
        type: string
      native_lang:
        type: string
      played_games_count:
        type: integer
      winning_percentage:
        type: number
      xp:
        type: integer
    type: object
  genprotos.VocabulariesGARes:
    properties:
      vocabularies:
        items:
          $ref: '#/definitions/genprotos.ExerciseGResUReq'
        type: array
    type: object
  handlers.MyDataResponse:
    properties:
      user:
        $ref: '#/definitions/models.User'
      user_data:
        $ref: '#/definitions/genprotos.UserDataGRes'
    type: object
  models.User:
    properties:
      email:
        type: string
      id:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
info:
  contact: {}
paths:
  /exercise/{id}:
    get:
      consumes:
      - application/json
      description: Get an exercise by its ID
      parameters:
      - description: Exercise ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/genprotos.ExerciseGResUReq'
        "400":
          description: Invalid exercise ID
          schema:
            type: string
        "500":
          description: Server error
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: Get exercise
      tags:
      - Exercise
  /exercises:
    get:
      consumes:
      - application/json
      description: Get all exercises
      parameters:
      - description: Lesson ID
        in: query
        name: lesson_id
        type: string
      - description: Exercise type
        in: query
        name: type
        type: string
      - description: limit
        in: query
        name: limit
        type: integer
      - description: offset
        in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/genprotos.ExerciseGARes'
        "400":
          description: Invalid parameters
          schema:
            type: string
        "500":
          description: Server error
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: Get all exercises
      tags:
      - Exercise
  /leaderboard:
    get:
      description: Get the leaderboard sorted by XP
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/genprotos.LeadboardRes'
            type: array
        "500":
          description: Internal Server Error
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: Get Leaderboard
      tags:
      - leaderboard
  /lesson/{id}:
    get:
      consumes:
      - application/json
      description: Get a lesson by it's UUID
      parameters:
      - description: Leesson ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/genprotos.LessonCReqGRes'
        "400":
          description: Invalid lesson ID
          schema:
            type: string
        "500":
          description: Server error
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: Get lesson
      tags:
      - Lesson
  /lessons:
    get:
      consumes:
      - application/json
      description: Get all lessons
      parameters:
      - description: name
        in: query
        name: name
        type: string
      - description: lang_1
        in: query
        name: lang_1
        type: string
      - description: lang_2
        in: query
        name: lang_2
        type: string
      - description: level
        in: query
        name: level
        type: string
      - description: order
        in: query
        name: order
        type: integer
      - description: limit
        in: query
        name: limit
        type: integer
      - description: offset
        in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/genprotos.LessonGARes'
        "400":
          description: Invalid parameters
          schema:
            type: string
        "500":
          description: Server error
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: Get all lessons
      tags:
      - Lesson
  /mydata:
    get:
      consumes:
      - application/json
      description: Retrieves user data
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.MyDataResponse'
        "400":
          description: Invalid user ID
          schema:
            type: string
        "500":
          description: Server error
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: Get User Data
      tags:
      - UserData
  /start-test:
    post:
      consumes:
      - application/json
      description: Start a test by checking the answers of the provided quiz requests
        against the exercises of the specified lesson
      parameters:
      - description: Test Check Request
        in: body
        name: YourAnswers
        required: true
        schema:
          $ref: '#/definitions/genprotos.TestCheckReqForSwagger'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/genprotos.TestResultRes'
        "500":
          description: Server error
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: Start a test
      tags:
      - quiz
  /vocabularies:
    get:
      consumes:
      - application/json
      description: Gets vocabularies
      parameters:
      - description: Lesson ID
        in: query
        name: lesson_id
        type: string
      - description: Exercise type
        in: query
        name: type
        type: string
      - description: limit
        in: query
        name: limit
        type: integer
      - description: offset
        in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/genprotos.VocabulariesGARes'
        "400":
          description: Invalid parameters
          schema:
            type: string
        "500":
          description: Server error
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: Get Vocabularies
      tags:
      - Vocabulary
  /vocabulary/{id}:
    delete:
      consumes:
      - application/json
      description: Deletes an exercise from the vocabulary
      parameters:
      - description: Exercise ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: Exercise deleted from vocabulary
          schema:
            type: string
        "400":
          description: Invalid exercise ID
          schema:
            type: string
        "500":
          description: Server error
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: Delete from Vocabulary
      tags:
      - Vocabulary
    post:
      consumes:
      - application/json
      description: Adds an exercise to the vocabulary
      parameters:
      - description: Exercise ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Exercise added to vocabulary
          schema:
            type: string
        "400":
          description: Invalid exercise ID
          schema:
            type: string
        "500":
          description: Server error
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: Add to Vocabulary
      tags:
      - Vocabulary
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
