version: '3.8'

services:
  budget_service:
    container_name: budget_cont 
    build: ./
    ports:
      - "50051:50051"
    networks:
      - global-network
    depends_on:
      - mongo_service
      - zookeeper_service
      - kafka_service

  mongo_service:
    container_name: mongo
    image: mongo:latest
    networks:
      - global-network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - "27018:27017"

  zookeeper_service:
    image: confluentinc/cp-zookeeper:7.4.4
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    networks:
      - global-network

  kafka_service:
    image: confluentinc/cp-kafka:7.4.4
    container_name: kafka
    depends_on:
      - zookeeper_service
    ports:
      - 29092:29092
    networks:
      - global-network
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1


networks:
  global-network:
    external: true
    name: global-network
    driver: bridge

volumes:
  db: